{% set name = "forest_lite" %}
{% set version = "0.17.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MetOffice/forest-lite/archive/v{{ version }}.tar.gz
  sha256: a20cd8e74935de6939d6a986bcc094355689c44d35fc7a61082e2d4f0ce82e6b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - forest_lite = forest_lite.cli:app

requirements:
  host:
    - python >=3.6
    - pip
    - nodejs
  run:
    - python >=3.6
    - fastapi
    - typer
    - bokeh
    - uvicorn
    - aiofiles
    - cartopy_offlinedata
    - datashader
    - graphene
    - h5netcdf
    - iris

test:
  imports:
    - forest_lite

about:
  home: https://github.com/MetOffice/forest-lite
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Forecast and observation research and evaluation survey tool
  description: |
    FOREST-Lite is a weather data web viewer with a Python data server
    and JS client. It works with Python 3.7+.
  doc_url: https://metoffice.github.io/forest-lite/
  dev_url: https://github.com/MetOffice/forest-lite

extra:
  recipe-maintainers:
    - andrewgryan
