{% set name = "forest_lite" %}
{% set version = "0.16.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MetOffice/forest-lite/archive/v{{ version }}.tar.gz
  sha256: c82b73888aef7c0801a40c6bac1d8f482d2dac26903307aa4ba95171e2a5539b

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - forest_lite = forest_lite.cli:app

requirements:
  host:
    - python >=3.6
    - pip
    - nodejs
  run:
    - python >=3.6
    - fastapi
    - uvicorn
    - aiofiles
    - python-multipart
    - xarray
    - forest
    - h5netcdf
    - datashader
    - cartopy_offlinedata
    - typer
    - proj >=7.1.0
    - pyproj >=2.6
    - nodejs >=14.11.0
    - pygrib
    - passlib
    - python-jose

test:
  imports:
    - forest_lite

about:
  home: https://github.com/MetOffice/forest-lite
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: 'Forecast and observation research and evaluation survey tool'
  description: |
    FOREST-Lite is a weather data web viewer with a Python data server
    and JS client. It works with Python 3.7+.
  doc_url: https://metoffice.github.io/forest-lite/
  dev_url: https://github.com/MetOffice/forest-lite

extra:
  recipe-maintainers:
    - andrewgryan
